[options]
# admin_passwd = odoo1978               # remover se linha abaixo funcionar
admin_passwd = ${ODOO_ADMIN_PASSWORD}
db_host = db
db_port = 5432
# db_user = odoo                        # remover se linha abaixo funcionar
db_user = ${POSTGRES_USER}
# db_password = odoo1978                # remover se linha abaixo funcionar
db_password = ${POSTGRES_PASSWORD}    
addons_path = /mnt/extra-addons
